apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: stream-recorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      initContainers:
        - name: superset-init
          image: apache/superset:3.1.3
          env:
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: SUPERSET_SECRET_KEY
            - name: SUPERSET_SQLALCHEMY_DATABASE_URI
              value: postgresql+psycopg2://streamuser:streampassword@streamrecorder-db-rw:5432/streamrecord
            - name: SUPERSET_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: SUPERSET_ADMIN_USERNAME
            - name: SUPERSET_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: SUPERSET_ADMIN_PASSWORD
            - name: SUPERSET_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: SUPERSET_ADMIN_EMAIL
          command:
            - /bin/bash
            - -c
            - |
              superset db upgrade
              superset fab create-admin \
                --username $SUPERSET_ADMIN_USERNAME \
                --firstname Admin \
                --lastname User \
                --email $SUPERSET_ADMIN_EMAIL \
                --password $SUPERSET_ADMIN_PASSWORD
              superset init
      containers:
        - name: superset
          image: apache/superset:3.1.3
          env:
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: SUPERSET_SECRET_KEY
            - name: SUPERSET_SQLALCHEMY_DATABASE_URI
              value: postgresql+psycopg2://streamuser:streampassword@streamrecorder-db-rw:5432/streamrecord
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.5"