apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: stream-recorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset:3.1.3
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.5"
          env:
            - name: SUPERSET_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: superset-secret
                  key: SUPERSET_ADMIN_USERNAME
            - name: SUPERSET_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superset-secret
                  key: SUPERSET_ADMIN_PASSWORD
            - name: SUPERSET_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: superset-secret
                  key: SUPERSET_ADMIN_EMAIL
          ports:
            - containerPort: 8088