apiVersion: v1
kind: Service
metadata:
  name: superset-svc
  namespace: stream-recorder
spec:
  type: NodePort
  selector:
    app: superset
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30088